version: 0.0
os: linux
files:
  - source: /
    destination: /var/www
  - source: /core/scripts/centest_uwsgi.conf
    destination: /etc/init
hooks:
  BeforeInstall:
    - location: core/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: core/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: core/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: core/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu